# Generated by Django 2.2.5 on 2019-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZapparUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField(default=0)),
                ('fname', models.CharField(default='John', max_length=255)),
                ('lname', models.CharField(default='Doe', max_length=255)),
                ('phone', models.CharField(default='+4411 2358 13 21', max_length=255)),
            ],
            options={
                'db_table': 'zappar_users',
            },
        ),
    ]
