# Generated by Django 2.2.5 on 2019-09-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190925_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapparusers',
            name='gender',
            field=models.CharField(default='male', max_length=255),
        ),
        migrations.AlterField(
            model_name='zapparusers',
            name='title',
            field=models.CharField(default='mr', max_length=255),
        ),
    ]
